#!/usr/bin/env python3
"""
Generates compact repo intelligence map.
Sources (in priority): package.json, src-tauri/tauri.conf.json, capabilities/default.json, .wolf/anatomy.md if exists, CLAUDE.md
Output: references/sage-architecture.md + JSON to stdout + cache .wolf/sage-map.json when run inside repo
"""
import json, os, re, sys, hashlib
from pathlib import Path

def read_json(p: Path):
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except: return None

def scan_repo(repo: Path) -> dict:
    pkg = read_json(repo / "package.json") or {}
    tauri = read_json(repo / "src-tauri" / "tauri.conf.json") or {}
    cap = read_json(repo / "src-tauri" / "capabilities" / "default.json")

    # modules
    tweaks_mod = repo / "src-tauri" / "src" / "tweaks" / "mod.rs"
    modules = []
    if tweaks_mod.exists():
        txt = tweaks_mod.read_text(encoding="utf-8", errors="ignore")
        # crude: pub mod xxx
        modules = sorted(set(re.findall(r"pub mod (\w+)", txt)))[:30]

    # build commands
    scripts = pkg.get("scripts", {})
    build_cmds = {k:v for k,v in scripts.items() if any(x in k for x in ["build","test","tauri","verify","wiring","ipc","security","type-check","lint"])}
    deps = list(pkg.get("dependencies", {}).keys())[:15]

    # tauri info
    product = tauri.get("productName", "SageTweaks")
    identifier = tauri.get("identifier", "com.sagetweaks.desktop")
    targets = tauri.get("bundle", {}).get("targets", [])
    external_bin = tauri.get("bundle", {}).get("externalBin", [])

    # capabilities
    perms_count = 0
    auto = repo / "src-tauri" / "permissions" / "autogenerated"
    if auto.exists():
        perms_count = len(list(auto.glob("*.toml")))

    # claude guidance
    claude_md = ""
    for cand in [repo/"CLAUDE.md", repo/"AGENTS.md"]:
        if cand.exists():
            claude_md = cand.read_text(encoding="utf-8", errors="ignore")[:2000]
            break

    # git branch + frequently modified areas + entry points
    branch = ""
    freq_modified = []
    entry_points = []
    tests_summary = {}
    try:
        import subprocess
        r = subprocess.run(["git","rev-parse","--abbrev-ref","HEAD"], cwd=repo, capture_output=True, text=True, timeout=5)
        if r.returncode==0: branch = r.stdout.strip()
        # frequently modified in last 100 commits
        r2 = subprocess.run(["git","log","--pretty=format:","--name-only","-n","100"], cwd=repo, capture_output=True, text=True, timeout=5)
        if r2.returncode == 0:
            from collections import Counter
            cnt = Counter([l.strip() for l in r2.stdout.splitlines() if l.strip()])
            freq_modified = [f"{f} ({n})" for f,n in cnt.most_common(8)]
        # entry points
        for cand in ["src/main.tsx","src/App.tsx","src-tauri/src/main.rs","src-tauri/src/lib.rs"]:
            if (repo / cand).exists():
                entry_points.append(cand)
        # tests
        import glob
        vitest = len(list((repo / "src").rglob("*.test.*"))) if (repo / "src").exists() else 0
        rust_tests = len(list((repo / "src-tauri" / "src").rglob("*.rs"))) if (repo / "src-tauri").exists() else 0
        qa = (repo / "qa" / "vm-matrix").exists()
        tests_summary = {"vitest_files": vitest, "rust_files": rust_tests, "qa_vm": qa}
    except: pass

    # dependencies detailed
    deps = list(pkg.get("dependencies", {}).keys())[:20]
    dev_deps = list(pkg.get("devDependencies", {}).keys())[:10]
    tauri_config = {
        "bundle_targets": targets,
        "externalBin": external_bin,
        "csp": tauri.get("app",{}).get("security",{}).get("csp","")[:200] if tauri.get("app") else "",
        "updater": bool(tauri.get("plugins",{}).get("updater")),
    }
    # important config
    important_config = []
    for f in ["src-tauri/tauri.conf.json","src-tauri/Cargo.toml","src-tauri/capabilities/default.json","package.json","AGENTS.md","CLAUDE.md"]:
        if (repo / f).exists():
            important_config.append(f)
    # windows-specific code detection
    windows_code = []
    for cand in ["src-tauri/src/tweaks","src-tauri/src/system","src-tauri/src/firmware"]:
        if (repo / cand).exists():
            windows_code.append(cand)
    # subsystem ownership (heuristic)
    subsystem_ownership = {}
    if (repo / "src-tauri" / "src" / "tweaks").exists():
        subsystem_ownership["tweaks"] = "src-tauri/src/tweaks/* → tweak catalog/impls"
    if (repo / "src-tauri" / "src" / "security").exists():
        subsystem_ownership["security"] = "src-tauri/src/security/* → auth/privilege"
    if (repo / "src" / "components").exists():
        subsystem_ownership["frontend"] = "src/components/* → React views"
    if (repo / "qa").exists():
        subsystem_ownership["qa"] = "qa/vm-matrix/* → Windows VM validation"

    return {
        "product": product,
        "identifier": identifier,
        "version": pkg.get("version",""),
        "branch": branch,
        "tauri_config": tauri_config,
        "targets": targets,
        "externalBin": external_bin,
        "permissions_autogenerated": perms_count,
        "tweak_modules_sample": modules,
        "scripts": build_cmds,
        "deps": deps,
        "dev_deps": dev_deps,
        "capabilities_default": cap.get("permissions", [])[:10] if cap else [],
        "claude_preview": claude_md[:800],
        "entry_points": entry_points,
        "frequently_modified": freq_modified,
        "tests_summary": tests_summary,
        "important_config": important_config,
        "windows_code": windows_code,
        "subsystem_ownership": subsystem_ownership,
        "repo": str(repo),
    }

def write_markdown(repo: Path, data: dict, out_path: Path):
    md = f"""# Sage Architecture — Auto Map

> Generated by `scripts/context/repo-map.py`. Repo evidence wins over memory.
> Repo: `{data['repo']}` | Version: `{data['version']}` | Branch: `{data['branch']}`

## Product
- **{data['product']}** (`{data['identifier']}`) — bundle targets: `{', '.join(data['targets']) or 'nsis'}`
- External binaries: `{', '.join(data['externalBin']) or 'none'}`
- Autogenerated permissions: `{data['permissions_autogenerated']}` toml files

## Build / Test Commands (from package.json)
"""
    for k,v in data["scripts"].items():
        md += f"- `{k}`: `{v}`\n"
    md += f"""
## Entry Points
- {', '.join(data.get('entry_points',[])[:5]) or 'not detected'}

## Tweak Modules (sample from src-tauri/src/tweaks/mod.rs)
- {', '.join(data['tweak_modules_sample'][:15]) or 'not scanned'}

## Dependencies
- deps: {', '.join(data.get('deps',[])[:10])}
- dev: {', '.join(data.get('dev_deps',[])[:5])}

## Tauri Config
- bundle: {data.get('tauri_config',{}).get('bundle_targets')}
- externalBin: {data.get('tauri_config',{}).get('externalBin')}
- updater: {data.get('tauri_config',{}).get('updater')}
- windows code: {', '.join(data.get('windows_code',[]))}

## Important Config
- {', '.join(data.get('important_config',[])[:8])}

## Frequently Modified (last 100 commits)
- {chr(10)+'- '.join(data.get('frequently_modified',[])[:8]) if data.get('frequently_modified') else 'no git history'}

## Tests
- {data.get('tests_summary',{})}

## Key Paths
- Frontend: `src/` (React 19, Vite, Zustand, TanStack Query)
- Backend: `src-tauri/src/` (Rust, Tauri v2, commands/, tweaks/impls/, security/, gaming/, module_tweak_runtime/)
- Config: `src-tauri/tauri.conf.json` (perMachine NSIS, updater endpoints)
- Capabilities: `src-tauri/capabilities/default.json` → `permissions/default.toml` → `permissions/autogenerated/*.toml`
- QA: `qa/vm-matrix/`, `scripts/*check.mjs`

## Verification Quick Map
- Frontend: `pnpm type-check` → `pnpm lint` → `pnpm test`
- Rust/Tauri: `cargo check` / `cargo test` (in src-tauri) → `pnpm wiring:check` → `pnpm ipc:check` → `pnpm security:policy`
- Windows: validate registry path + rollback snapshot before apply

## Change Detection
- Map hash: `{data.get('hash','')} ` — re-run repo-map only if `git diff --stat` or `package.json`/`tauri.conf.json` changed.

## Conventions (CLAUDE.md preview)
```
{data['claude_preview'][:700]}
```

## Known Pitfalls
- `src-tauri/.cargo/config.toml` [profile.release] was removed 2026-08-19 — Cargo.toml is authoritative.
- `bundle.windows.wix` block dead — only `nsis` target runs.
- Never invent registry paths / service names — verify via local tooling or docs.
- Performance claims require `hypothesis → measured → compare` with baseline.
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")

def main():
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--repo", default=".", help="repo path")
    p.add_argument("--out", default="", help="markdown out path")
    args = p.parse_args()

    plugin_root = Path(__file__).resolve().parents[2]
    repo = Path(args.repo).resolve()
    # auto-detect sage-tweaks repo if --repo is plugin itself
    if not (repo / "package.json").exists() and (Path("C:/Users/SageOS/Documents/GitHub/sage-tweaks") / "package.json").exists():
        # still prefer explicit repo, but allow plugin as reference base
        if args.repo == ".":
            # try cwd
            cwd = Path.cwd()
            if (cwd / "package.json").exists():
                repo = cwd

    data = scan_repo(repo)
    # hash for staleness
    h = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()[:12]
    data["hash"] = h

    # write markdown to plugin references
    out_md = Path(args.out) if args.out else plugin_root / "references" / "sage-architecture.md"
    write_markdown(repo, data, out_md)

    # cache in repo .wolf if possible
    wolf_cache = repo / ".wolf" / "sage-map.json"
    try:
        if repo.exists() and (repo / ".git").exists():
            wolf_cache.parent.mkdir(exist_ok=True)
            wolf_cache.write_text(json.dumps(data, indent=2), encoding="utf-8")
    except: pass

    print(json.dumps(data, indent=2))
    print(f"\n# markdown written to {out_md}", file=sys.stderr)
    if wolf_cache.exists():
        print(f"# cache written to {wolf_cache}", file=sys.stderr)

if __name__ == "__main__":
    main()
